[theme]
primaryColor="#10789c"
backgroundColor="#00000e"
secondaryBackgroundColor="#08081E"
textColor="#ffffff"      # Pure white for clarity
font = "sans serif"


    
[server]
enableCORS = false
enableXsrfProtection = true
    
[browser]
gatherUsageStats = false

# Custom Colors for Alerts and Status
[theme.colors]
success = "#43A047"
warning = "#FFA000"
danger = "#E53935"
accent = "#FF7043"