# This file is used for storing sensitive information like API keys
# Do not commit this file to version control

# Example (replace with your actual secrets):
COHERE_API_KEY = "WqwXPqNRPpcZVYHLJXkH6sT5laichlQJzzDkfSqV"

# openai_api_key = "your-openai-api-key-here"
# other_secret = "your-other-secret-here"